---
title: "Power Rankings Week 3"
draft: true
---

# #12: The One Inch Wonder <span style="color: red;">↑ 1</span>
The One Inch Wonder is back in their rightful spot in the bottom of the league after a historic choke this week against Macho Mel. After being down during the entire match, The One Inch Wonder managed to pull ahead with one point in the dwindling minutes. But alas, it was not to be. Inch pulled off the choke of the century and in the final possible moment gave up the lead for a Mel victory. Remember last week when we send Dion Lewis wasn’t going to be much help? Guess which team completely blew off our advice and started him anyways? His 1.5 points sunk Inch’s comeback efforts. If they had only started Carlos Hyde like any reasonable team would do; they would have come away with the victory. It is truly wondrous how The One Inch Wonder always manages to lose even with Mahomes having monster games. 

# #11: LeGarrette Cunt <span style="color: red;">↑ 2</span>
Half of Cunt’s starting lineup could not break 5 points. That is not a recipe for success in anyone’s book. After a strong first week it looked like Darius Slayton was going to be worthy of being the most overhyped player in the offseason. After the last two weeks, it looks like it might have just been hyper after all. Slayton has completely failed to meet expectations, even with Sterling Shepard out. Cunt’s biggest problem continues to be at receiver. Outside of Keenan Allen there is not a single good fantasy receiving option on the team. There’s a lot of work to be done here if Cunt wants to get a win this season.

# #10: Malik Turner’s Playoff Catch % <span style="color: red;">↑ 5</span>
Hobo News Network has seen enough to decide that Malik Turner’s Playoff Catch % got robbed and crippled their roster with the blockbuster trade last week. Let’s do a little math. Team Hide and Zeke scored 113.5 points. Malik Turner’s playoff catch % scored 110 points. If you subtract them, you’ll find a difference of 3.5 points. Remember that. Let’s do a bit more math. Garbage Time Commander Deshaun Watson, who if you remember Turner acquired by giving up James Robinson and Carson Wentz, scored 16 points. Carson Wentz, the player Turner traded away last week, scored 21. That’s a difference of five points. We’ll let you come to your own conclusions. 
<br>
Oh and giving up James Robinson was also an awful idea. The Hobos send their regards. 

# #9: Team Hide and Zeke <span style="color: green;">↓ 3</span>
Despite an uncharacteristically poor game from Lamar Jackson, Team Hide and Zeke managed to narrowly come out with their first win of the season behind Mike Evans legendary 2 yard, 2 touchdown game. 

# #8: Macho Mel <span style="color: aqua;">═</span>
Macho Mel may be the worst 2-1 team in league history. They have won both of their matches with a combined 1.5 points and have by far the lowest point total in the league. Yet despite being an awful team by all metrics, Mel’s uncanny luck has led to an uncontested 2nd place position in the Hardly Trying division. The road is suddenly about to get harder for Mel though. Mel’s last three opponents have three wins COMBINED. Their next opponent (the Hyperhobos) are one of two teams with a 3-0 record. Additionally, Mel has yet to address the horrid state of their wide receiving group. Mel is in for some trouble if Julio Jones is out or unable to perform at 100% this weekend. 

# #7: Belchers Pistol Offense <span style="color: green;">↓ 3</span>
Belchers Pistol Offense may be in for a rough week if the Titans-Steelers game gets cancelled, but for the meantime Belcher gets to celebrate their first win in the biggest upset of the season so far. 
<br>
That was enough celebrating, back to reality. This is still a very flawed team. Take a look at the bench, no one is scoring. Zero depth. Thielen is having a rough stretch of games, and to put the final nail on the coffin: Godwin is hurt. Again. 

# #6: Team Striegel <span style="color: aqua;">═</span>
Striegel lost unsurprisingly, but they remain at #6. Striegel still doesn’t have an RB2 and OBJ is still disappointing fantasy owners around the league. Once Davante Adams comes back, he, Chubb, and Allen should be able to carry Striegel to an occasional victory. But at the moment, Striegel is far from fielding a competitive playoff contending team. 

# #5: Sarah Please Take Me Back<span style="color: green;"> ↓ 2</span>
Sarah didn’t have a bad week all things considered. Sure they lost against the unbeatable Hobos, but they still managed to bring in the 4th highest score total of the week. Despite being 1-2 this team still doesn’t have much reason to panic and should right the ship soon enough. 

# #4: No Kap <span style="color: red;">↑ 1</span>
No Kap leaves the ranks of the unbeaten in a surprising lose to Belchers Pistol Offense. Dalvin Cook was the only standout performance for Kap. Cooper, Ridley, and Gould had decent games but outside of that, not a single player showed up for Kap. It may be time for Kap to start figuring out how to replace Joe Mixon. Mixon has proven that he was definitely not worth his 2nd round draft price. His production has been that of a flex player at best and it is definitely hurting this team. No Kap still has a chance to be competitive in Cam Newton returns to the levels of production he had in weeks 1 and 2, but there is work to be done here.

# #3: Moneymongol Autodraft<span style="color: green;"> ↓ 1</span>
Tyler Lockett had a monster 32.5 point game and doomed LeGarrette Cunt to the only winless record in the league. Despite that, the points we made last week continue to haunt this team. Another week, another lackluster showing from both T.Y Hilton and AJ Green. In addition to that, David Johnson has been showing signs of cooling off and Chris Carson is likely to be out at least this week. So with Carson out, Cohen out for the season, and CMC still out, Kareem Hunt is going to have to move up to RB2 and one of Moneycock’s mediocre bench receivers will have to occupy the flex spot. Autodraft may be in trouble. 

# #2: Gelato #66 <span style="color: aqua;">═</span>
Gelato is one of two remaining undefeated teams alongside the Hobos. This past week against Toaster Striegel, Russell Wilson put up another 5 TD game to lead the charge. The rest of lineup put up solid numbers to round out the scoring… except for TE. Again. Gelato has been playing musical chairs these past few weeks with the TE spot. With Jordan Reed out for the foreseeable future (like always), OJ Howard is now the only TE left on the roster. 
<br>
Counting on OJ Howard never ends well. Still, Gelato is stacked enough (by that we mean Russell Wilson) that they should be the favorites for the majority of their matches. 

# #1: Hobolopolis Hyperhobos <span style="color: aqua;">═</span>
They said the Hobos were done. They said the Hobos were crazy to trade away their second draft pick, mere days after their first draft pick was lost for the season. They said the Hobos were cursed and would never be able to be successful given their injuries. Yet here we are. Despite losing at least 1 player partway through every single game and always being at a numbers disadvantage, the Hobos are 3-0. Despite playing in the historically dominant try hard division, the Hobos have at least a 1 game lead over everyone else in the division. Despite losing their projected top two stars in Saquon Barkley and George Kittle, the Hobos are better than ever and not only put up their personal season best in scoring this week, they put up the best point total in the week period. Behind the unstoppable trio of James Robinson, Gesicki, and Fitzmagic’s beard, there isn’t a single team that looks stronger than the Hyperhobos.





```{r, echo=FALSE, message=FALSE, warning = FALSE}

          
          
```

