---
title: "Power Rankings Week 2"
draft: true
---

# #12: Team Hide and Zeke <span style="color: red;">↑ 1</span>
Hide and Zeke narrowly came out the loser in this year’s early edition of the toilet bowl. Team Hide and Zeke took a risk by starting Scotty Miller and Mike Williams, and it backfired big time. Hide and Zeke lost by a total of 7 points. If either of them had been left on the bench, and Brandin Cooks had been started instead, Team Hide and Zeke would have won with 2.5 points. Poor coaching was the downfall in an otherwise solid roster.

# #11: The One Inch Wonder <span style="color: green;">↓ 1</span>
The One Inch Wonder may have won their only game of the season this past week. Bell is out, White is out, Gore and Hyde are mediocre at best. When Antonio Gibson is by far the best active RB on the roster, the team has a huge problem. The One Inch Wonder did recently pick up Dion Lewis though.
<br><br>
He's not going to be much help.

# #10: Belchers Pistol Offense <span style="color: aqua;">═</span>
Belchers Pistol Offense is riding the Patriots D all the way to the basement of the league. If it weren’t for Prescott having a career day against the pitiful Falcons, this matchup would have looked a lot worse for Belcher. Which is saying something considering they ended up losing by almost 40 points anyways. Belchers Pistol Offense is not in a good spot right now. The RB2 spot desperately needs to be addressed because Myles Gaskin is not the answer. The bench is still awful. Godwin may be back, but Brady hasn't exactly been lighting up the scoreboard.  

# #9: LeGarrette Cunt <span style="color: red;">↑ 3</span>
For some reason LeGarrette Cunt went into the game without a tight end in the lineup. Darren Waller ended up scoring 22 to give Cunt the win in bench points. The match would have been a massacre regardless of whether or not he was in the lineup though; it was a complete one-sided beatdown. LeGarrette Cunt doesn't have much to work with. The entire roster is filled with subpar fantasy talent without any breakout potential. No matter where you look there just isn't any reason for hope on the roster. 

# #8: Macho Mel <span style="color: red;">↑ 3</span>
Macho Mel's receiving group has been absolutely decimated in just two short weeks. AJ Brown and Marquisse Brown were shipped out of town for Julio Jones. Jones was nonexistent against Dallas and may be out with a hamstring injury this week. Campbell is done for the season and was already dropped. Sterling Shepard is on IR and will miss at least the next three games. Here's what Mel has left: an old DeSean Jackson in a bad Eagles offense, Robert Woods, and a couple unproven scrubs in Tre'Quan and Pittman Jr. Mel was by far the lowest scoring team last week, and their point total might not be much better this week. Macho Mel is really lucky to be going up against The One Inch wonder.

# #7: Sarah Please Don't Let Hill Beat More Women <span style="color: green;">↓ 2</span>
Sarah Please had a strong showing against Mel and most importantly made it through the NFL apocalypse relatively unscathed. Out of the teams ranked 12-6, we feel like Sarah has the best chance to climb the rankings and reach the top four. McClaurin has proven to be a very solid receiver and Juju is showing signs of being special. Sarah has to be careful though, because a single injury could tank this team. Management completely whiffed on bench players; there is zero depth on this team and any injury in the starting lineup will be too much for the team to overcome. 

# #6: Toaster Striegel <span style="color: green;">↓ 2</span>
Striegel did some Striegel stuff and won this week while looking completely unimpressive. Maybe if he fused the three Lions RB's into one he'll have one worth starting. 

# #5: Malik Turners Playoff Catch % <span style="color: green;">↓ 2</span>
Malik Turners Playoff Catch % may have choked and lost to the Hobos despite having a numbers advantage, but recent moves improve their standing by two spots. Malik Turners Playoff Catch % got three good starters (assuming they're healthy enough to play) out of their blockbuster deal with the Hobolopolis Hyperhobos in exchange for the <strong>GOAT JAMES ROBINSON</strong> and some other guys. This team had so many holes not even the <strong>GOAT JAMES ROBINSON</strong> could save it. Kittle, Chark, and Watson (once they're healthy enough to play) will be strong additions and help stop this sinking ship from going down completely. 

# #4: Autocock Draftmongol <span style="color: aqua;">═</span>
Good job Cock-killer, you murdered your #1 pick. McCaffery was so tired of carrying this team his sprained he own ankle to take a break for several weeks. Luckily for Draftcocker, this roster is well equipped to handle a prolonged absence. Hunt, Carson, and David Johnson are more than enough to hold down the fort for a while. Moneydraft still has an issue with receivers though. Neither Hilton or Green are living up to the hype leaving the position rather weak. The both of them combined for a total of 7 points this past week. 

# #3: No Kap <span style="color: aqua;">═</span>
Kap overcame a zero point game from William "The Scrub" Fuller and narrowly edged out the dastardly Cockmongols. Cam Newton and Melvin Gordon continue to look strong and no starters were seriously hurt (despite the bench being completely wiped out). There aren't any negatives to nitpick about on this team. Yet. 

# #2: Gelato #61 <span style="color: aqua;">═</span>
Gelatin #52 dominated week 2 and came away with the weeks high score at 170 points. Led by a monstrous 17 points from Younghoe Koo (and 42 from Jones), Keratin #41 mercilessly ripped Garrette LeCunt apart. While the team is currently rolling, there are several cracks that could eventually become Melatonin's downfall. The tight end group on this team is STILL awful. ZERO points from Gronk this past week. Gronk was replaced in this week's lineup by Mo Alie-cox, which I don't think needs an explanation for why that is an awful decision. Gurley wasn't too hot either. Time will tell whether Prime Gurley or Kneeless Gurley will be more common this season. 

# #1: The Undying, Unmatched, Unstoppable Hobolopolis Hyperhobos <span style="color: aqua;">═</span>
Despite all the injuries sustained by this Hobo squad, they powered through and withstood a late barrage by Alvin Kamara to gain sole possession of the Try Hard division with a 2-0 record. It is truly impressive how this team fights back in the face of adversity. Unfortunately, not all the Hobos were true Hyperhobo quality. Some had to be cut off for the betterment of the Hobo ecosystem. Barkley, gone. Kittle, gone. Chark, Gone. Garbage time commander Watson, gone. The Hobos are now under command of Mikey "Ultra God" Gesicki and the future first ballot hall of famer James Robinson. The future truly looks bright for the most dominant force in Ray Rice's Left Hook.


```{r, echo=FALSE, message=FALSE, warning = FALSE}

          
          
```

