---
title: Week 1 Power Rankings
author: Charles Charlestone IV
date: '2020-09-17'
slug: week-1-power-rankings
categories: []
tags: []
---

# #12: The One Inch Wonder
The One Inch Wonder was a catastrophic failure in their week one matchup against the Hobos. That shouldn’t come as a surprise, given the F grade they received on their draft. Where to even start with this team. To begin with, the Hobos two starting RUNNING BACKS had more receiving yards than Inch’s starting wide receivers. Kelce and Mahomey were good as expected, but everyone else was a complete disaster. The highest scoring starting receiver or running back on The One Inch Wonder was James white, with a whopping 6.5 points. As you may guess, The One Inch Wonder was massacred and put up the lowest score of the week with a sad 83 points. The future doesn’t look much better for Inch. Bell and Thomas are out for the foreseeable future (not that they were doing much before getting hurt anyways), Gibson, Boyd, and Johnson were duds, and there weren’t any promising signs from the bench. The One Inch Wonder is clearly the worst team in the league right now. 

# #11: Hide and Zeke
The other team to get an F grade on the draft also did not do much to prove us wrong. We said this team was too top heavy and lacked depth. What happened this week? Elliot and Jackson combined for almost half the teams points, where Evans sat on the bench and did next to nothing. Decaf stepped up with a solid 17 points, but the rest of the team was nowhere to be found. They somehow choked away a massive lead and allowed Macho Mel to come back and win with a single point. Embarrassing. Luckily for Hide and Zeke, they get an easy matchup against The One Inch Wonder this week to figure things out.

