---
title: 'Hobo Draft Guide: QB'
author: Howard Van Tinkle
date: '2020-08-31'
slug: hobo-draft-preview-qb
categories:
  - Draft
tags: []
Description: 'Your sabotage free guide to a successful season: QB Edition'
---
# A Brief Introduction
Welcome to the new and improved Hobo News Network, your #1 source of unbiased Ray Rice's Left Hook news! Check in throughout the season for draft guides, trade reviews, game previews, and much more. 

The 2020-2021 RRLH draft is tentatively scheduled for Sunday September 6 (according to Commissioner Jose). 
Over the next couple days we will be publishing guides for each position, to ensure you are adequately prepared and ready to dominate. Today we will be going over Quarterbacks. 

# The importance of a good QB
Many say running backs are the most important position in fantasy. Others say wide recievers. The truth is, QB's are just as important. No one has ever won a title with some like Andy Dalton or Jared Goff, you need a true star like Fitzpatrick to have a shot. The importance of a good QB can not be understated. 

# Young QB's are overrated
Every year there's young, breakout talent like Mahomes two years ago and Lamar last year that can single handily carry a team to the playoffs. It can make one think, *'wow I should target young QB's that look like they could become a superstar and lead my team to a championship'*. BAD. NO. You want to be safe. You want to target QB's that will always give you consistent production. Like Brady. Brady has been a decent fantasy QB since 1845, you know what you're getting out of him. Other good options are guys like Matt Ryan and Matt Stafford. CONSISTENT. Don't take risks. 


# Keep in mind: Be like Hugo
If you wait too long, your dream QB will be gone and your season will be doomed. Just look at how much success Team Hide and Zeke had last year after they drafted Deshaun Watson with the first pick in the 4th round. Hide and Zeke is the sort of team you want to emulate. There is no such thing as reaching for a QB too early.

# Avoid the hype
Every single year every major draft guide and so called fantasy 'experts' hype up the same small group of guys. Stay off the bandwagon, and under no circumstances draft the following five guys:

* <strong>Russell Wilson:</strong> Why would you want a game manager with a garbage tier offensive line? 
* <strong>Patrick Mahomes:</strong> Don't underestimate superbowl hangovers, Mahomes is due for a huge decline this year. 
* <strong>Lamar Jackson:</strong> Lamar is next in line for the Madden curse, and give how historically awful Madden 21 is, you can expect the curse to hit hard this year. 
* <strong>Deshaun Watson:</strong> Watson is too tired and beat up from carrying Hide and Zeke last season, there's no way he can keep up the same production this year. 
* <strong>Drew Brees:</strong> Too old and injury prone. His prime is long past. 

# Remember: Hobo News Network is here for you!
Carefully follow our advice to the letter and we can 100% guarantee you'll land in the coveted runner-up position after the Hobos win the championship. 